# deploy_ingress.yaml - Deploys the ingress controller and web app ingress
- name: Deploy Keycloak ingress controller and web app ingress
  hosts: localhost
  tasks:
    - name: Apply Keycloak  ingress controller and web app ingress
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/ingress.yaml
        namespace: ingress-nginx