# deploy_web.yaml - Deploys coredns-custom
- name: Deploy coredns-custom
  hosts: localhost
  tasks:
    - name: Apply coredns-custom
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/coredns-custom.yaml
        namespace: kube-system