# deploy_rbac.yaml - Deploys RBAC for ingress-nginx controller
- name: Deploy ingress-nginx RBAC and patch
  hosts: localhost
  tasks:

    - name: Apply ingress-nginx RBAC
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/rbac.yaml
        namespace: ingress-nginx