- name: Deploy Keycloak static web application ConfigMap
  hosts: localhost
  tasks:
    - name: Apply Keycloak deployment web ConfigMap
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/configmap.yaml
        namespace: keycloak-app
    - name: Patch CoreDNS ConfigMap for keycloak.web.com and auth.web.com
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: coredns
            namespace: kube-system
          data:
            Corefile: |
              .:53 {
                  errors
                  health
                  hosts {
                      10.0.6.199 keycloak.web.com
                      10.0.18.183 auth.web.com
                      fallthrough
                  }
                  kubernetes cluster.local in-addr.arpa ip6.arpa {
                      pods insecure
                      fallthrough in-addr.arpa ip6.arpa
                  }
                  prometheus :9153
                  forward . /etc/resolv.conf
                  cache 30
                  loop
                  reload
                  loadbalance
              }
