# deploy_web.yaml - Deploys the static web app to the AKS cluster
- name: Deploy Keycloak static web application
  hosts: localhost
  tasks:
    - name: Apply Keycloak deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/coredns-custom.yaml
        namespace: kube-system