# deploy_postgres.yaml - Deploys PostgreSQL for Keycloak
- name: Deploy Keycloak postgres
  hosts: localhost
  tasks:
    - name: Apply Keycloak postgres deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/postgres.yaml
        namespace: keycloak-app

