- name: Deploy Keycloak rbac
  hosts: localhost
  tasks:
    - name: Apply Keycloak rbac
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/rbac.yaml
        namespace: ingress-nginx
