# deploy_keycloak.yaml - Deploys Keycloak to the AKS cluster
- name: Deploy Keycloak
  hosts: localhost
  tasks:
    - name: Apply Keycloak deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/keycloak.yaml
        namespace: keycloak-app
