- name: Deploy Kubernetes Secrets
  hosts: localhost
  tasks:
    - name: Apply secrets deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../../kube/secrets.yaml
        namespace: keycloak-app 